@host=http://localhost:5210
POST {{host}}/sneakers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDA1OWYzOC04Mzc2LTQyNGEtODc4MC05Yjg5MGY5ZTUwMTUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiJiNTMzMWIwZC0wMzU2LTRlZTgtYjQ0ZC03OTkxZTM2OTAzYzciLCJleHAiOjE3MDA0NjQwMjMsImlzcyI6IlNuZWFrZXIgQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXIgQ29sbGVjdGlvbiJ9.4ofBdqfJh4CzLa9-Jfr6kkit8VC96CSGQzpWok6eBwI
Content-Type: application/json

{
    "name": "Nike Air Max 90",
    "brand": "Nike",
    "size": 42,
    "price": 100,
    "year": 2019,
    "rate": 4
}
