@host=http://localhost:5210
POST {{host}}/sneakers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWYxN2ZkMy1lYzNhLTQwOWYtYTMyOS1kNTE5NGU0M2VkY2MiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiI5ZGMxN2RlYi1jNjY2LTQyZGQtYWJiMC1mMTdlNThjZmE2MDUiLCJleHAiOjE3MDA0NjU0MzcsImlzcyI6IlNuZWFrZXIgQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXIgQ29sbGVjdGlvbiJ9._grLTOWZ9DdoNUYZYL7CqSRGQECeT53C3tJCNZP-Ayg
Content-Type: application/json

{
    "name": "Nike Air Max 90",
    "brand": "Nike",
    "size": 42,
    "price": 100,
    "year": 2019,
    "rate": 4
}
