@host=http://localhost:5210
DELETE  {{host}}/sneakers/190a5fcd-66db-4be1-adb1-709a543e85d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTQ2N2ZmMi00OTVjLTQ2MjgtYjBjNy01MzEzMmEwZTMxYzIiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiJkZTIxYzkxMy0yNDYxLTQxNjEtYTA2My04YzlhM2MyYmVkMWQiLCJleHAiOjE3MDA1MjUyNTIsImlzcyI6IlNuZWFrZXIgQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXIgQ29sbGVjdGlvbiJ9.GkSSmA2j1bO5OFqTgCydDQhrH7sW9qqNgOT-IeYfeuc
