@host=http://localhost:5210
GET {{host}}/sneakers?filterValue=xxx&sortBy=year
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NWM4NjJhZC04ZGMwLTQ3OWEtODkyMy1lMmZhYTY3NWQ1OTciLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiI3YmFkZDMzZi1mOTczLTQyYjAtODMxMi1iYzg5YjBlOTQ0NjQiLCJleHAiOjE3MDA0NTE0NjcsImlzcyI6IlNuZWFrZXIgQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXIgQ29sbGVjdGlvbiJ9.CjmqI_ornlCtKH6W6XPAknlh-HxZTbCX2GeLKtYVakg
