@host=http://localhost:5210
PUT {{host}}/sneakers/5161c50e-8789-4749-8f98-923d7ec0709c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjczZTA4ZC03NDY5LTRiYTMtYTE5YS01YjVjNDUyNmJmM2IiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJqdGkiOiIwMjlhZTM2Zi04ODRhLTRmMWQtOTI5Mi1iNWNhYThmZGI3YTUiLCJleHAiOjE3MDA0OTI4MDcsImlzcyI6IlNuZWFrZXIgQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXIgQ29sbGVjdGlvbiJ9.kwWSligkfQQL2C6h6BOJRRT0SeDE6ox2tka0pMM9nvM
Content-Type: application/json

{
    "name": "Nike Air Max 90",
    "brand": "Nike 2",
    "size": 42,
    "price": 100,
    "year": 2019,
    "rate": 4
}